### PR TITLE
get target from url for debugging

### PR DESCRIPTION
**Pull request by westerschmal**
## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

### CODE REVIEW

**Comment by mefjush** [comment]
hi Wester, what's the intended use case? Why can't you simply add `/inwhatever-you-like` to your request? The end result would be the same, no?

**Comment by westerschmal** [comment]
Hey Mateusz, it's very handy on publishers where we don't control the Prebid js configuration but do want to add the target to the request.

**Comment by mefjush** [comment]
I'd like to understand what is the intended usecase afterwards? You add some custom string to the "in" parameter. What's next? Where will you look it up then?

**Comment by mefjush** [comment]
Also, would such a tampermonkey script solve that for you:
```
// ==UserScript==
// @name         Prebid.js debug param injector
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://*/?pbjs_debug=true&adhese_pbjs_debug=true
// @grant        none
// @run-at       document-start
// ==/UserScript==

(function() {
    'use strict';

    // Your code here...
    var tryUpdate = function() {
        if (typeof pbjs !== 'undefined') {
            console.log("prebid found!");
            var bidderFilter = function bidderFilter(adunits) {
                for (let i in adunits) {
                    if (adunits[i].bids) {
                        for (let b in adunits[i].bids) {
                            var bid = adunits[i].bids[b];
                            if (bid.bidder == "adhese") {
                                if (!("in" in bid.params.data)) {
                                    bid.params.data["in"] = [];
                                }
                                bid.params.data["in"].push("wester123");
                            }
                        }
                    }
                }
            };
            pbjs.onEvent('beforeRequestBids', bidderFilter);
        } else {
            console.log("waiting for prebid...");
            setTimeout(tryUpdate, 10);
        }
  };
  tryUpdate();

})();
```

**Comment by westerschmal** [comment]
Hey Mateusz, good thinking, thanks. 

One of the things we are trying to achieve, is that anyone can force an ad response on any page where our adapter is integrated. 
For example, if a (dale) advertiser (without any technical knowledge) wants to see their ad on a specific page, we can send them a url with a target as a query string param, and on our end target the ad they want to see against that param.

**Pull request closed without merging**
